name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install Hugo
        run: |
          wget https://github.com/goharbor/harbor/releases/download/v2.3.0/harbor-offline-installer-v2.3.0.tgz
          tar -xvzf harbor-offline-installer-v2.3.0.tgz
          sudo cp harbor/hugo /usr/local/bin/
      - name: Build the site
        run: hugo
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public    
      - name: Vue App to Github Pages
        # You may pin to the exact commit or the version.
        # uses: StruggleYang/VuePagesAction@b1d5654c25f30f4c640cfc20fa7e24e71de7c215
        uses: StruggleYang/VuePagesAction@2.0.0
        with:
          # Use yarn to build
          useyarn: true # optional, default is true
          # Your custom domain
          # cname: # optional, default is none
          
          
